import type {
  Agendamento,
  ComentarioFormando,
  Compromisso,
  DashboardStats,
  EventoFormando,
  Formacao,
  Formando,
  GradeFormativa,
  HistoricoFormando,
  GrupoFormacao,
  PlanoFormativo,
  PresencaFormacao,
  Usuario,
} from "@/types";

export const mockGruposFormacao: GrupoFormacao[] = [
  {
    id: "m1",
    nome: "Morada São João Bosco",
    localReuniao: "Rua das Flores, 123 — Fortaleza/CE",
    tipo: "estruturado",
    nivelFormativo: "pre-discipulado",
    formadorId: "u2",
    planoId: "p1",
    gradeId: "g1",
    ativo: true,
    criadoEm: "2024-01-10",
  },
  {
    id: "m2",
    nome: "Morada Nossa Senhora",
    localReuniao: "Av. da Paz, 456 — Fortaleza/CE",
    tipo: "estruturado",
    nivelFormativo: "discipulado",
    formadorId: "u3",
    planoId: "p2",
    ativo: true,
    criadoEm: "2024-02-01",
  },
];

export const mockUsuarios: Usuario[] = [
  {
    id: "u1",
    nome: "Admin",
    email: "admin@exemplo.org",
    perfil: "formador_geral",
    ativo: true,
    criadoEm: "2024-01-10",
  },
  {
    id: "u0",
    nome: "Ana Costa",
    email: "ana.costa@exemplo.org",
    perfil: "administrador",
    ativo: true,
    criadoEm: "2024-01-12",
  },
  {
    id: "u2",
    nome: "Carlos Mendes",
    email: "carlos.mendes@exemplo.org",
    perfil: "formador_comunitario",
    grupoFormacaoId: "m1",
    ativo: true,
    criadoEm: "2024-02-15",
  },
  {
    id: "u3",
    nome: "Maria Silva",
    email: "maria.silva@exemplo.org",
    perfil: "formador_comunitario",
    grupoFormacaoId: "m2",
    ativo: true,
    criadoEm: "2024-03-01",
  },
];

export const mockFormandos: Formando[] = [
  {
    id: "f1",
    nome: "Lucas Pereira",
    dataNascimento: "2000-05-15",
    estadoCivil: "solteiro",
    modalidade: "presencial",
    nivelFormativo: "pre-discipulado",
    dataIngresso: "2024-03-01",
    telefone: "(85) 99999-0001",
    email: "lucas.pereira@email.com",
    ativo: true,
    grupoFormacaoId: "m1",
    totalFormacoes: 114,
    formacoesRealizadas: 89,
    progressoEtapas: [
      {
        nivel: "pre-discipulado",
        formacoesComunitariasRealizadas: 82,
        retirosComunitariosRealizados: 1,
        retirosPessoaisRealizados: 6,
        iniciouEm: "2024-03-01",
      },
    ],
  },
  {
    id: "f2",
    nome: "Juliana Martins",
    dataNascimento: "1998-11-22",
    estadoCivil: "solteiro",
    modalidade: "presencial",
    nivelFormativo: "discipulado",
    dataIngresso: "2023-01-15",
    telefone: "(85) 99999-0002",
    email: "juliana.martins@email.com",
    ativo: true,
    grupoFormacaoId: "m1",
    totalFormacoes: 114,
    formacoesRealizadas: 71,
    progressoEtapas: [
      {
        nivel: "pre-discipulado",
        formacoesComunitariasRealizadas: 104,
        retirosComunitariosRealizados: 2,
        retirosPessoaisRealizados: 8,
        iniciouEm: "2023-01-15",
        concluiuEm: "2025-01-20",
      },
      {
        nivel: "discipulado",
        formacoesComunitariasRealizadas: 65,
        retirosComunitariosRealizados: 1,
        retirosPessoaisRealizados: 5,
        iniciouEm: "2025-01-20",
      },
    ],
  },
  {
    id: "f3",
    nome: "Rafael Souza",
    dataNascimento: "1995-08-10",
    estadoCivil: "casado",
    modalidade: "hibrida",
    nivelFormativo: "primeiras-promessas",
    dataIngresso: "2021-06-01",
    telefone: "(85) 99999-0003",
    email: "rafael.souza@email.com",
    ativo: true,
    grupoFormacaoId: "m2",
    totalFormacoes: 57,
    formacoesRealizadas: 52,
    progressoEtapas: [
      {
        nivel: "pre-discipulado",
        formacoesComunitariasRealizadas: 104,
        retirosComunitariosRealizados: 2,
        retirosPessoaisRealizados: 8,
        iniciouEm: "2021-06-01",
        concluiuEm: "2023-06-15",
      },
      {
        nivel: "discipulado",
        formacoesComunitariasRealizadas: 104,
        retirosComunitariosRealizados: 2,
        retirosPessoaisRealizados: 8,
        iniciouEm: "2023-06-15",
        concluiuEm: "2025-06-10",
      },
      {
        nivel: "primeiras-promessas",
        formacoesComunitariasRealizadas: 48,
        retirosComunitariosRealizados: 1,
        retirosPessoaisRealizados: 3,
        iniciouEm: "2025-06-10",
      },
    ],
  },
  {
    id: "f4",
    nome: "Fernanda Lima",
    dataNascimento: "2001-03-28",
    estadoCivil: "solteiro",
    modalidade: "presencial",
    nivelFormativo: "pre-discipulado",
    dataIngresso: "2024-03-01",
    telefone: "(85) 99999-0004",
    email: "fernanda.lima@email.com",
    ativo: true,
    grupoFormacaoId: "m1",
    totalFormacoes: 114,
    formacoesRealizadas: 54,
    progressoEtapas: [
      {
        nivel: "pre-discipulado",
        formacoesComunitariasRealizadas: 50,
        retirosComunitariosRealizados: 1,
        retirosPessoaisRealizados: 3,
        iniciouEm: "2024-03-01",
      },
    ],
  },
  {
    id: "f5",
    nome: "Thiago Alves",
    dataNascimento: "1993-12-05",
    estadoCivil: "casado",
    modalidade: "presencial",
    nivelFormativo: "formacao-permanente",
    dataIngresso: "2018-01-01",
    telefone: "(85) 99999-0005",
    email: "thiago.alves@email.com",
    ativo: true,
    grupoFormacaoId: "m2",
    totalFormacoes: 57,
    formacoesRealizadas: 49,
    progressoEtapas: [
      {
        nivel: "pre-discipulado",
        formacoesComunitariasRealizadas: 104,
        retirosComunitariosRealizados: 2,
        retirosPessoaisRealizados: 8,
        iniciouEm: "2018-01-01",
        concluiuEm: "2020-01-20",
      },
      {
        nivel: "discipulado",
        formacoesComunitariasRealizadas: 104,
        retirosComunitariosRealizados: 2,
        retirosPessoaisRealizados: 8,
        iniciouEm: "2020-01-20",
        concluiuEm: "2022-02-15",
      },
      {
        nivel: "primeiras-promessas",
        formacoesComunitariasRealizadas: 52,
        retirosComunitariosRealizados: 1,
        retirosPessoaisRealizados: 4,
        iniciouEm: "2022-02-15",
        concluiuEm: "2023-03-01",
      },
      {
        nivel: "formacao-permanente",
        formacoesComunitariasRealizadas: 45,
        retirosComunitariosRealizados: 1,
        retirosPessoaisRealizados: 3,
        iniciouEm: "2023-03-01",
      },
    ],
  },
  {
    id: "f6",
    nome: "Camila Rodrigues",
    dataNascimento: "1999-07-14",
    estadoCivil: "solteiro",
    modalidade: "online",
    nivelFormativo: "discipulado",
    dataIngresso: "2023-03-10",
    telefone: "(85) 99999-0006",
    email: "camila.rodrigues@email.com",
    ativo: true,
    grupoFormacaoId: "m2",
    totalFormacoes: 114,
    formacoesRealizadas: 43,
    progressoEtapas: [
      {
        nivel: "pre-discipulado",
        formacoesComunitariasRealizadas: 104,
        retirosComunitariosRealizados: 2,
        retirosPessoaisRealizados: 8,
        iniciouEm: "2023-03-10",
        concluiuEm: "2025-03-15",
      },
      {
        nivel: "discipulado",
        formacoesComunitariasRealizadas: 40,
        retirosComunitariosRealizados: 0,
        retirosPessoaisRealizados: 3,
        iniciouEm: "2025-03-15",
      },
    ],
  },
];

export const mockHistorico: HistoricoFormando[] = [
  {
    id: "h1",
    formandoId: "f1",
    agendamentoId: "ag5",
    formacaoTema: "Quem Sou Eu? — Identidade em Cristo",
    data: "2026-04-25",
    status: "realizada",
    presente: true,
    observacao: "Participou ativamente, demonstrou interesse e envolvimento com o grupo. Contribuiu com reflexões pessoais durante a partilha.",
  },
  {
    id: "h2",
    formandoId: "f4",
    agendamentoId: "ag5",
    formacaoTema: "Quem Sou Eu? — Identidade em Cristo",
    data: "2026-04-25",
    status: "realizada",
    presente: false,
    observacao: "Ausente sem justificativa prévia. Necessário acompanhar na próxima semana.",
  },
  {
    id: "h3",
    formandoId: "f3",
    agendamentoId: "ag4",
    formacaoTema: "Discernimento Vocacional",
    data: "2026-05-08",
    status: "realizada",
    presente: true,
    observacao: "Excelente participação, trouxe reflexões pessoais muito valiosas para o grupo.",
  },
  {
    id: "h4",
    formandoId: "f2",
    agendamentoId: "ag5",
    formacaoTema: "Quem Sou Eu? — Identidade em Cristo",
    data: "2026-04-25",
    status: "realizada",
    presente: true,
    observacao: "Boa participação e disposição. Demonstra adesão consistente ao plano formativo.",
  },
];

export const mockPlanos: PlanoFormativo[] = [
  {
    id: "p1",
    nome: "Plano Formativo 2024 — Pré-Discipulado",
    objetivos:
      "Introduzir o formando aos princípios fundamentais da vida comunitária e espiritual.",
    fundamentacao:
      "Baseado nos documentos fundacionais da Comunidade Dom Bosco e nos evangelhos.",
    eixos: [
      { id: "ep1-1", nome: "Identidade", objetivo: "Ajudar o formando a descobrir sua identidade como filho de Deus e membro da comunidade.", intervaloEncontros: "Encontros 1 a 3", cargaHoraria: 6, areaFormacao: "Espiritual" },
      { id: "ep1-2", nome: "Oração", objetivo: "Ensinar os fundamentos da vida de oração pessoal e comunitária.", intervaloEncontros: "Encontros 4 a 6", cargaHoraria: 6, areaFormacao: "Espiritual" },
      { id: "ep1-3", nome: "Comunidade", objetivo: "Formar para a vivência comunitária autêntica e o sentido de pertencimento.", intervaloEncontros: "Encontros 7 a 9", cargaHoraria: 6, areaFormacao: "Humana" },
      { id: "ep1-4", nome: "Missão", objetivo: "Despertar a consciência missionária e o compromisso apostólico.", intervaloEncontros: "Encontros 10 a 12", cargaHoraria: 6, areaFormacao: "Apostólica" },
    ],
    nivelFormativo: "pre-discipulado",
    vigenciaInicio: "2024-01-01",
    vigenciaFim: "2024-12-31",
    status: "ativo",
    criadoEm: "2023-11-15",
    atualizadoEm: "2024-01-10",
  },
  {
    id: "p2",
    nome: "Plano Formativo 2024 — Discipulado",
    objetivos: "Aprofundar a vida de fé e o comprometimento comunitário.",
    fundamentacao: "Documentos do Discipulado Comunitário Dom Bosco.",
    eixos: [
      { id: "ep2-1", nome: "Fé", objetivo: "Aprofundar o conhecimento e a vivência da fé católica no contexto comunitário.", intervaloEncontros: "Encontros 1 a 4", cargaHoraria: 8, areaFormacao: "Espiritual" },
      { id: "ep2-2", nome: "Serviço", objetivo: "Desenvolver a espiritualidade do serviço e da doação ao próximo.", intervaloEncontros: "Encontros 5 a 8", cargaHoraria: 8, areaFormacao: "Apostólica" },
      { id: "ep2-3", nome: "Palavra", objetivo: "Aprofundar a relação com a Sagrada Escritura e a Tradição da Igreja.", intervaloEncontros: "Encontros 9 a 12", cargaHoraria: 8, areaFormacao: "Espiritual" },
      { id: "ep2-4", nome: "Sacramentos", objetivo: "Vivenciar os sacramentos como encontro pessoal com Cristo e a Igreja.", intervaloEncontros: "Encontros 13 a 16", cargaHoraria: 8, areaFormacao: "Espiritual" },
    ],
    nivelFormativo: "discipulado",
    vigenciaInicio: "2024-01-01",
    vigenciaFim: "2024-12-31",
    status: "ativo",
    criadoEm: "2023-11-15",
    atualizadoEm: "2024-01-10",
  },
  {
    id: "p3",
    nome: "Plano Formativo 2025 — Primeiras Promessas",
    objetivos: "Aprofundar o comprometimento definitivo com a vida comunitária e apostólica.",
    fundamentacao: "Revisão e atualização dos planos anteriores.",
    eixos: [
      { id: "ep3-1", nome: "Espiritualidade", objetivo: "Aprofundar a vida espiritual para o comprometimento definitivo com a comunidade.", intervaloEncontros: "Encontros 1 a 3", cargaHoraria: 9, areaFormacao: "Espiritual" },
      { id: "ep3-2", nome: "Formação Humana", objetivo: "Trabalhar a maturidade humana e afetiva necessária ao comprometimento definitivo.", intervaloEncontros: "Encontros 4 a 6", cargaHoraria: 9, areaFormacao: "Humana" },
      { id: "ep3-3", nome: "Missão", objetivo: "Preparar o formando para o compromisso missionário definitivo e público.", intervaloEncontros: "Encontros 7 a 9", cargaHoraria: 9, areaFormacao: "Apostólica" },
      { id: "ep3-4", nome: "Comunhão", objetivo: "Aprofundar os vínculos de comunhão, unidade e corresponsabilidade comunitária.", intervaloEncontros: "Encontros 10 a 12", cargaHoraria: 9, areaFormacao: "Comunitária" },
    ],
    nivelFormativo: "primeiras-promessas",
    vigenciaInicio: "2025-01-01",
    vigenciaFim: "2025-12-31",
    status: "em-revisao",
    criadoEm: "2024-10-01",
    atualizadoEm: "2024-11-20",
  },
];

export const mockGrades: GradeFormativa[] = [
  {
    id: "g1",
    nome: "Grade Pré-Discipulado 2024",
    planoId: "p1",
    planoNome: "Plano Formativo 2024 — Pré-Discipulado",
    nivelFormativo: "pre-discipulado",
    vigenciaInicio: "2024-03-01",
    vigenciaFim: "2024-11-30",
    versao: "1.0",
    eixos: [
      { id: "e1", nome: "Identidade", descricao: "Quem sou eu?", gradeId: "g1", ordem: 1, cor: "#6366F1" },
      { id: "e2", nome: "Oração", descricao: "Como me relaciono com Deus?", gradeId: "g1", ordem: 2, cor: "#3B82F6" },
      { id: "e3", nome: "Comunidade", descricao: "Como vivo em comunidade?", gradeId: "g1", ordem: 3, cor: "#10B981" },
      { id: "e4", nome: "Missão", descricao: "Para que fui chamado?", gradeId: "g1", ordem: 4, cor: "#F59E0B" },
    ],
    etapas: [
      { id: "et1", nome: "Encontro com Deus", descricao: "Primeira etapa de abertura", eixoId: "e1", ordem: 1, cargaHoraria: 2 },
      { id: "et2", nome: "Vida de Oração", descricao: "Fundamentos da oração", eixoId: "e2", ordem: 1, cargaHoraria: 2 },
      { id: "et3", nome: "Vida Comunitária", descricao: "Vivência em grupo", eixoId: "e3", ordem: 1, cargaHoraria: 2 },
    ],
    totalFormacoes: 8,
    ativo: true,
    criadoEm: "2024-01-15",
  },
];

export const mockFormacoes: Formacao[] = [
  {
    id: "fm1",
    tema: "Quem Sou Eu? — Identidade em Cristo",
    objetivo: "Apresentar ao formando sua identidade como filho de Deus.",
    descricao: "Reflexão profunda sobre a identidade cristã e comunitária.",
    nivelFormativo: "pre-discipulado",
    tipoFormacao: "comunitaria",
    eixoId: "e1",
    eixoNome: "Identidade",
    etapaId: "et1",
    etapaNome: "Encontro com Deus",
    formadorId: "u2",
    formadorNome: "Carlos Mendes",
    cargaHoraria: 2,
    modalidade: "presencial",
    vezesUtilizada: 3,
    criadoEm: "2024-01-20",
  },
  {
    id: "fm2",
    tema: "A Oração como Diálogo com Deus",
    objetivo: "Ensinar os fundamentos da vida de oração.",
    descricao: "Como estabelecer uma rotina de oração e intimidade com Deus.",
    nivelFormativo: "pre-discipulado",
    tipoFormacao: "comunitaria",
    eixoId: "e2",
    eixoNome: "Oração",
    formadorId: "u2",
    formadorNome: "Carlos Mendes",
    cargaHoraria: 2,
    modalidade: "presencial",
    vezesUtilizada: 5,
    criadoEm: "2024-01-20",
  },
  {
    id: "fm3",
    tema: "Vida Comunitária — Essência e Desafios",
    objetivo: "Compreender o valor e a vocação da vida comunitária.",
    descricao: "A comunidade como lugar de crescimento e missão.",
    nivelFormativo: "discipulado",
    tipoFormacao: "comunitaria",
    eixoId: "e3",
    eixoNome: "Comunidade",
    formadorId: "u3",
    formadorNome: "Maria Silva",
    cargaHoraria: 3,
    modalidade: "presencial",
    vezesUtilizada: 8,
    criadoEm: "2024-02-01",
  },
  {
    id: "fm4",
    tema: "Discernimento Vocacional",
    objetivo: "Ajudar o formando a discernir seu chamado.",
    descricao: "Ferramentas espirituais para o discernimento da vocação.",
    nivelFormativo: "primeiras-promessas",
    tipoFormacao: "comunitaria",
    formadorId: "u3",
    formadorNome: "Maria Silva",
    cargaHoraria: 4,
    modalidade: "hibrida",
    vezesUtilizada: 4,
    criadoEm: "2024-02-10",
  },
];

export const mockAgendamentos: Agendamento[] = [
  {
    id: "ag1",
    formacaoId: "fm1",
    formacaoTema: "Quem Sou Eu? — Identidade em Cristo",
    nivelFormativo: "pre-discipulado",
    tipoFormacao: "comunitaria",
    formadorId: "u2",
    formadorNome: "Carlos Mendes",
    dataInicio: "2026-05-15T19:00:00",
    dataFim: "2026-05-15T21:00:00",
    local: "Sede Comunitária — Sala A",
    status: "confirmada",
    participantes: 12,
    criadoEm: "2026-04-20",
  },
  {
    id: "ag2",
    formacaoId: "fm2",
    formacaoTema: "A Oração como Diálogo com Deus",
    nivelFormativo: "pre-discipulado",
    tipoFormacao: "comunitaria",
    formadorId: "u2",
    formadorNome: "Carlos Mendes",
    dataInicio: "2026-05-22T19:00:00",
    dataFim: "2026-05-22T21:00:00",
    local: "Sede Comunitária — Sala A",
    status: "agendada",
    participantes: 12,
    criadoEm: "2026-04-20",
  },
  {
    id: "ag3",
    formacaoId: "fm3",
    formacaoTema: "Vida Comunitária — Essência e Desafios",
    nivelFormativo: "discipulado",
    tipoFormacao: "comunitaria",
    formadorId: "u3",
    formadorNome: "Maria Silva",
    dataInicio: "2026-05-18T14:00:00",
    dataFim: "2026-05-18T17:00:00",
    local: "Sede Comunitária — Auditório",
    status: "agendada",
    participantes: 20,
    criadoEm: "2026-04-25",
  },
  {
    id: "ag4",
    formacaoId: "fm4",
    formacaoTema: "Discernimento Vocacional",
    nivelFormativo: "primeiras-promessas",
    tipoFormacao: "comunitaria",
    formadorId: "u3",
    formadorNome: "Maria Silva",
    dataInicio: "2026-05-08T19:00:00",
    dataFim: "2026-05-08T23:00:00",
    local: "Casa de Retiro",
    status: "realizada",
    participantes: 8,
    criadoEm: "2026-04-10",
  },
  {
    id: "ag5",
    formacaoId: "fm1",
    formacaoTema: "Quem Sou Eu? — Identidade em Cristo",
    nivelFormativo: "pre-discipulado",
    tipoFormacao: "comunitaria",
    formadorId: "u2",
    formadorNome: "Carlos Mendes",
    dataInicio: "2026-04-25T19:00:00",
    dataFim: "2026-04-25T21:00:00",
    local: "Sede Comunitária — Sala A",
    status: "realizada",
    participantes: 10,
    criadoEm: "2026-03-30",
  },
  {
    id: "ag6",
    formacaoId: "fm2",
    formacaoTema: "A Oração como Diálogo com Deus",
    nivelFormativo: "pre-discipulado",
    tipoFormacao: "comunitaria",
    formadorId: "u2",
    formadorNome: "Carlos Mendes",
    dataInicio: "2026-04-15T19:00:00",
    dataFim: "2026-04-15T21:00:00",
    local: "Sede Comunitária — Sala A",
    status: "cancelada",
    participantes: 0,
    criadoEm: "2026-03-20",
  },
];

export const mockPresencas: PresencaFormacao[] = [
  { id: "pr1", agendamentoId: "ag5", formacaoTema: "Quem Sou Eu? — Identidade em Cristo", data: "2026-04-25", formandoId: "f1", formandoNome: "Lucas Pereira", nivelFormativo: "pre-discipulado", presente: true },
  { id: "pr2", agendamentoId: "ag5", formacaoTema: "Quem Sou Eu? — Identidade em Cristo", data: "2026-04-25", formandoId: "f4", formandoNome: "Fernanda Lima", nivelFormativo: "pre-discipulado", presente: false, justificativa: "Viagem" },
  { id: "pr3", agendamentoId: "ag5", formacaoTema: "Quem Sou Eu? — Identidade em Cristo", data: "2026-04-25", formandoId: "f2", formandoNome: "Juliana Martins", nivelFormativo: "discipulado", presente: true },
  { id: "pr4", agendamentoId: "ag4", formacaoTema: "Discernimento Vocacional", data: "2026-05-08", formandoId: "f3", formandoNome: "Rafael Souza", nivelFormativo: "primeiras-promessas", presente: true },
  { id: "pr5", agendamentoId: "ag4", formacaoTema: "Discernimento Vocacional", data: "2026-05-08", formandoId: "f5", formandoNome: "Thiago Alves", nivelFormativo: "formacao-permanente", presente: true },
  { id: "pr6", agendamentoId: "ag4", formacaoTema: "Discernimento Vocacional", data: "2026-05-08", formandoId: "f6", formandoNome: "Camila Rodrigues", nivelFormativo: "discipulado", presente: false, justificativa: "Compromisso de trabalho" },
];

export const mockComentarios: ComentarioFormando[] = [
  {
    id: "c1",
    formandoId: "f1",
    formandoNome: "Lucas Pereira",
    formadorId: "u2",
    texto: "Lucas demonstrou boa adesão nas últimas formações. Participa ativamente das discussões e mostra interesse genuíno no processo formativo.",
    tipo: "progresso",
    criadoEm: "2026-05-02",
  },
  {
    id: "c2",
    formandoId: "f4",
    formandoNome: "Fernanda Lima",
    formadorId: "u2",
    texto: "Fernanda tem demonstrado dificuldade em comparecer às formações presenciais. Conversa agendada para entender as limitações e buscar alternativas.",
    tipo: "dificuldade",
    criadoEm: "2026-05-05",
  },
  {
    id: "c3",
    formandoId: "f2",
    formandoNome: "Juliana Martins",
    formadorId: "u2",
    texto: "Excelente adesão ao plano formativo. Juliana já completou 13 das 15 formações previstas para este semestre.",
    tipo: "adesao",
    criadoEm: "2026-05-07",
  },
  {
    id: "c4",
    formandoId: "f3",
    formandoNome: "Rafael Souza",
    formadorId: "u3",
    texto: "Rafael está muito próximo de concluir a etapa de Primeiras Promessas. Recomenda-se agendar conversa de discernimento.",
    tipo: "observacao",
    criadoEm: "2026-05-09",
  },
  {
    id: "c5",
    formandoId: "f6",
    formandoNome: "Camila Rodrigues",
    formadorId: "u3",
    texto: "Camila tem demonstrado dificuldades para equilibrar a vida formativa com compromissos profissionais. Precisa de acompanhamento mais próximo.",
    tipo: "dificuldade",
    criadoEm: "2026-05-10",
  },
];

export const mockCompromissos: Compromisso[] = [
  {
    id: "cp1",
    formadorId: "u2",
    titulo: "Conversa de acompanhamento — Fernanda Lima",
    descricao: "Entender as dificuldades de presença e buscar alternativas para continuar o processo formativo.",
    dataInicio: "2026-05-14T18:00:00",
    dataFim: "2026-05-14T19:00:00",
    local: "Sede Comunitária",
    tipo: "individual",
    formandoId: "f4",
    formandoNome: "Fernanda Lima",
    criadoEm: "2026-05-05",
  },
  {
    id: "cp2",
    formadorId: "u2",
    titulo: "Reunião de abertura do semestre — Morada São João Bosco",
    descricao: "Apresentação do calendário formativo do segundo semestre para todos os formandos da morada.",
    dataInicio: "2026-06-01T19:30:00",
    dataFim: "2026-06-01T21:00:00",
    local: "Sede Comunitária — Auditório",
    tipo: "geral",
    criadoEm: "2026-05-10",
  },
  {
    id: "cp3",
    formadorId: "u3",
    titulo: "Discernimento vocacional — Rafael Souza",
    descricao: "Conversa sobre o próximo passo na jornada formativa e possibilidade de Primeiras Promessas.",
    dataInicio: "2026-05-16T17:00:00",
    dataFim: "2026-05-16T18:30:00",
    local: "Sala de Reuniões",
    tipo: "individual",
    formandoId: "f3",
    formandoNome: "Rafael Souza",
    criadoEm: "2026-05-09",
  },
];

export const mockEventosFormando: EventoFormando[] = [];

export const mockDashboard: DashboardStats = {
  totalAgendadas: 3,
  totalRealizadas: 18,
  totalCanceladas: 2,
  taxaRealizacao: 90,
  totalFormandos: 42,
  formandosAtivos: 38,
  evolucaoMensal: [
    { mes: "Dez", agendadas: 4, realizadas: 3 },
    { mes: "Jan", agendadas: 6, realizadas: 5 },
    { mes: "Fev", agendadas: 8, realizadas: 7 },
    { mes: "Mar", agendadas: 7, realizadas: 7 },
    { mes: "Abr", agendadas: 5, realizadas: 4 },
    { mes: "Mai", agendadas: 6, realizadas: 3 },
  ],
  porNivel: [
    { nivel: "pre-discipulado", quantidade: 14, percentual: 33 },
    { nivel: "discipulado", quantidade: 12, percentual: 29 },
    { nivel: "primeiras-promessas", quantidade: 9, percentual: 21 },
    { nivel: "formacao-permanente", quantidade: 7, percentual: 17 },
  ],
  proximasFormacoes: mockAgendamentos.filter(
    (a) => a.status === "agendada" || a.status === "confirmada"
  ),
};
